### ISSUE TITLE
Error while running training

### ISSUE THREAD

**Issue by karnabhc** [Ruifeng-Zhou24/AdaMatting#4]
[2020-04-24 08:14:09,629] INFO - Program runs in train mode
[2020-04-24 08:14:09,631] INFO - Loading network
[2020-04-24 08:14:13,367] INFO - Initializing data loaders
[2020-04-24 08:14:13,381] INFO - Start training from scratch
Traceback (most recent call last):
  File "main.py", line 361, in <module>
    main()
  File "main.py", line 350, in main
    train(args=args, logger=logger, device_ids=device_ids)
  File "main.py", line 100, in train
    L_overall.backward()
  File "/usr/local/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Expected isFloatingType(grads[i].scalar_type()) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.) (validate_outputs at /pytorch/torch/csrc/autograd/engine.cpp:476)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f3ff0b16536 in /usr/local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2d84cb7 (0x7f4030180cb7 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #2: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x548 (0x7f4030181d58 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #3: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7f4030183ce2 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::Engine::thread_init(int) + 0x39 (0x7f403017c359 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7f403c8bb998 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0xbbb2f (0x7f403d78db2f in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #7: <unknown function> + 0x7fa3 (0x7f403ea2dfa3 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x3f (0x7f403e7cf4cf in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by Ruifeng-Zhou24** [comment]
Did you run training with cpu instead of gpu? I noticed "libtorch_cpu.so" appeared in the error message you provided. I didn't have a similar problem training on either single gpu or multiple gpus.

**Comment by karnabhc** [comment]
I am training on GPU inside a docker environment. The code is running on GPU as I have checked by issuing the nvtop command.

**Comment by karnabhc** [comment]
Any further updates on this? I am still stuck at the issue

**Comment by Ruifeng-Zhou24** [comment]
Sorry can't help you with that. I haven't met errors like this before. Maybe someone with similar issues could help you.

**Comment by Ruifeng-Zhou24** [comment]
I encountered a similar (but not exactly the same) error earlier. It occurred when I was using multiple GPUs and memory was not enough on one of the GPUs.

**Comment by karnabhc** [comment]
Okay, I am running this on a single gpu but I don't think that will be an issue. I have supplied the cuda arguments to the script accordingly. By the way, how much gpu size is recommended for training?

**Comment by saswat0** [comment]
Four 2080TI GPUs are being used by @Ruifeng-Zhou24

**Comment by shenghuokaikaixinxinjiuhao** [comment]
I also met the same mistake, and I only run this code on single GPU. So,  has any one solved it?

**Comment by karnabhc** [comment]
I am using a 16GB Tesla T4 for training in GCP environment. Prior to this, I was getting Out of Memory errors on GPU but after that I released GPU memory after every epoch using torch.cuda.empty_cache() and thereafter the problem with the OOM on GPU got solved but I am stuck on this. Tried every possible approach but cannot find a way around. Any help in this matter will be highly appreciated.

**Comment by myknowntime** [comment]
I think this is a problem with the pytorch version. I started with pytorch 1.5, when I changed the version to 1.4 the code works. So you can just change the pytorch version. My pytorch=1.4.0, torchvision=0.5.0, cudatoolkit=10.0. If you solved this problem, you can inform me.

**Comment by karnabhc** [comment]
@myknowntime after the latest git pull and with your versions I am facing the following errors-

Traceback (most recent call last):
  File "main.py", line 359, in <module>
    main()
  File "main.py", line 348, in main
    train(args=args, logger=logger, device_ids=device_ids)
  File "main.py", line 23, in train
    model = AdaMatting(in_channel=4)
  File "/home/karnabh/AdaMatting/net/adamatting.py", line 51, in __init__
    self.shortcut_shallow = self.br1(self.shortcut_shallow_intial)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/karnabh/AdaMatting/net/BR.py", line 13, in forward
    x_res = self.conv1(x)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not Sequential

**Comment by karnabhc** [comment]
@myknowntime after the latest git pull and with your versions I am facing the following errors-

Traceback (most recent call last):
File "main.py", line 359, in
main()
File "main.py", line 348, in main
train(args=args, logger=logger, device_ids=device_ids)
File "main.py", line 23, in train
model = AdaMatting(in_channel=4)
File "/home/karnabhc/AdaMatting/net/adamatting.py", line 51, in init
self.shortcut_shallow = self.br1(self.shortcut_shallow_intial)
File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in call
result = self.forward(*input, **kwargs)
File "/home/karnabhc/AdaMatting/net/BR.py", line 13, in forward
x_res = self.conv1(x)
File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in call
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
return self.conv2d_forward(input, self.weight)
File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not Sequential
